### ISSUE TITLE
Upgrade Ember version from 3.14 to 3.17

### ISSUE THREAD

**Issue by yoshifan** [fzerocentral/fzerocentral-web#12]
Or 3.18 if it gets released soon. 3.15 is Octane, so that might be a bigger-than-usual upgrade.

**Comment by locks** [comment]
3.18 is "being released" at the moment, I'd hope we have it out before next week.

**Comment by yoshifan** [comment]
PR #14 completes this without enabling Octane. See issue #15 for Octane.
